### ISSUE TITLE
Investigate how we get auto diff back

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#244]
For training this will be most useful, but one complication is that we can't seem to hook into TF's autograd subsystem as we're not subclassing tf.Tensors. What options do we have? Do they pose any challenges towards MPC? What happens when TF switches to eager mode by default?

**Comment by jvmancuso** [comment]
We now know how to do this.  Could use a healthy prototype, but here's what we'd need to use.

Replacing a single node:
- [`tf.RegisterGradient`](https://www.tensorflow.org/api_docs/python/tf/RegisterGradient)
- [`Graph.gradient_override_map`](https://www.tensorflow.org/api_docs/python/tf/Graph#gradient_override_map)

Subgraph:
- [`tf.custom_gradient`](https://www.tensorflow.org/api_docs/python/tf/custom_gradient) is a decorator for doing something similar to `tf.RegisterGradient` and `tf.Graph.gradient_override_map` more concisely and for a whole subgraph instead of a single node

Here's an example from Pond:
```python
@tf.custom_grad
def _mul_masked_masked(prot, x, y):
    assert isinstance(x, PondMaskedTensor), type(x)
    assert isinstance(y, PondMaskedTensor), type(y)

    a, a0, a1, alpha_on_0, alpha_on_1 = x.unwrapped
    b, b0, b1, beta_on_0, beta_on_1 = y.unwrapped

    with tf.name_scope("mul"):

        with tf.device(prot.crypto_producer.device_name):
            ab = a * b
            ab0, ab1 = prot._share_one_seed(ab)

        with tf.device(prot.server_0.device_name):
            alpha = alpha_on_0
            beta = beta_on_0
            z0 = ab0 + (a0 * beta) + (alpha * b0) + (alpha * beta)

        with tf.device(prot.server_1.device_name):
            alpha = alpha_on_1
            beta = beta_on_1
            z1 = ab1 + (a1 * beta) + (alpha * b1)

        z = PondPrivateTensor(prot, z0, z1, x.is_scaled or y.is_scaled)
        z = prot.truncate(z) if x.is_scaled and y.is_scaled else z

        def grad(dz):
                 return dz * y, dz * x

        return z, grad
```

The one thing I'm uncertain of here is that I'm not sure we can do this while still passing in `prot` as the first arg.  According to the docs, `tf.custom_gradient` generally expects its input function to have a signature `f(*x)`, where x is a tuple of tensors.  I'm not sure if that's a strict requirement, but if it is we'll probably want to loop that into the larger discussion of API improvements.  FWIW I think this could go well with previous thoughts around removing the Protocol abstraction, or at least allowing high-level tfe operations to be able to delegate their internals to whichever protocol they want/need to.

**Comment by mortendahl** [comment]
I suggest we close this up for now, wdyf @jvmancuso? Don't think we have found the perfect solution yet but maybe we've minimised the issue with #470 et al.?

**Comment by jvmancuso** [comment]
Agreed, we can work on having autograd for higher level layers and think about what to do on the general case later on
