### ISSUE TITLE
Different data owners

### ISSUE THREAD

**Issue by acs6610987** [tf-encrypted/tf-encrypted#490]
How can we use this library for "actual" different data owners?

For example, in the "simple-average" example:
https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/simple-average/run.py

It works fine because each owner's data is randomly generated in runtime:
`def provide_input() -> tf.Tensor:`
`return tf.random_normal(shape=(10,))`

Hence each machine will generate its own data during graph execution.

But what if the data should come from external sources, like a .csv file?
For example, 'inputter-0' has "data0.csv" on its machine 0, 'inputter-1' has "data1.csv" on its machine 1, etc... NOTE that these files are NOT on the machine that executes the script "run.py".

**Comment by mortendahl** [comment]
Hi @acs6610987, thanks for giving it a try!

Setting up local data loading is indeed possible, see e.g. the [federated learning](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/federated-learning/run.py) or the [MNIST](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/mnist/run.py) example.

Only caveat is that you have to use the [tf.data](https://www.tensorflow.org/guide/datasets) subsystem since code using e.g. numpy will not get properly distributed (you can't use `tf.py_func`).

**Comment by acs6610987** [comment]
Hi @mortendahl , thanks for the response!

I tried some simple code with tf.data, indeed, it solves my problem 👍

**Comment by mortendahl** [comment]
Happy to hear that -- let us know if you run into any more issues!

**Comment by sidharthramesh** [comment]
@acs6610987 can you please provide some code snippet with the simple-average that you got working with different data owners in remote config? Thank you

**Comment by mortendahl** [comment]
Hi @sidharthramesh, you must load the data using a TensorFlow construct such as a `tf.data.Dataset`, and this must be done inside e.g. a `tfe.local_computation`. The key point is that data loading must happen using a TensorFlow graph that can be sent to the data owner for execution.

See for instance the [MNIST example](https://github.com/tf-encrypted/tf-encrypted/blob/master/examples/mnist/run.py), where `provide_weights` calls `_build_data_pipeline` to build a TensorFlow data loading graph; since `provide_weights` is a local computation, all (and only) the TensorFlow code that happens inside of it will be executed on the data owner (defined by the `player_name` property of the enclosing class):

```python
def _build_data_pipeline(self):
  """Build a reproducible tf.data iterator."""

  def normalize(image, label):
    image = tf.cast(image, tf.float32) / 255.0
    return image, label

  def flatten(image, label):
    image = tf.reshape(image, shape=[self.FLATTENED_DIM])
    return image, label

  dataset = tf.data.TFRecordDataset([self.local_data_file])
  dataset = dataset.map(decode)
  dataset = dataset.map(normalize)
  dataset = dataset.map(flatten)
  dataset = dataset.repeat()
  dataset = dataset.batch(self.BATCH_SIZE)

  iterator = dataset.make_one_shot_iterator()
  return iterator

@tfe.local_computation
def provide_weights(self):
  with tf.name_scope('loading'):
    training_data = self._build_data_pipeline()

  with tf.name_scope('training'):
    parameters = self._build_training_graph(training_data)

  return parameters
```

**Comment by sidharthramesh** [comment]
@mortendahl thank you for the prompt response. I have made it work with `tf.data.TFRecordDataset`. Thank you! Great work btw! I'm new to the field of private machine learning and tf-encrypted is awesome! I am trying to deploy this in a [healthcare setting](https://medblocks.org/) where [differentially private SQL queries](https://github.com/uber/sql-differential-privacy) are executed on patient records (FHIR data) and then aggregated securely. Right now I'm just trying to use tf-encrypted to do the aggregation of counts (yes it's overkill but I'm trying to understand how to deploy tf-encrypted as well). In the future, I will be trying to implement machine learning models and support for various data streams especially, DICOM. Support for something like [TensorFlow-io](https://github.com/tensorflow/io) on different data owners would be a killer feature to have. 

Thank you again!

**Comment by mortendahl** [comment]
> I have made it work with tf.data.TFRecordDataset
Happy to hear it! Don't hesitate if another issue comes up.

> Great work btw! I'm new to the field of private machine learning and tf-encrypted is awesome! I am trying to deploy this in a healthcare setting where differentially private SQL queries are executed on patient records (FHIR data) and then aggregated securely. Right now I'm just trying to use tf-encrypted to do the aggregation of counts.

Thank you for the kind words, we appreciate it! Application sounds interesting and we'd be glad to help in any way we can.

> Support for something like TensorFlow-io on different data owners would be a killer feature to have.

I only know these components peripherally, but if they are building graphs (which it looks like) then there's a good chance it'll be easy to add support. Have you tried to use them already? Do you encounter specific errors?

**Comment by jvmancuso** [comment]
From what I can tell, TensorFlow IO aims to produce a `tf.data.Dataset` object from a variety of file system backends.  Since we don't make any assumptions about how this object is created, just that it exists, it should work without any adjustments to TFE (in theory!).  Would love to see an example/POC around this.
