### ISSUE TITLE
'base_layer_utils' has no attribute 'unique_layer_name'

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#526]
AttributeError: module 'tensorflow.python.keras.engine.base_layer_utils' has no attribute 'unique_layer_name'.

Happened on TF 1.14.0rc0.

**Comment by jvmancuso** [comment]
This is happening because the function in question (which is used in our keras engine) isn't covered by the TF stability guarantees

**Comment by mortendahl** [comment]
Any ideas for work-arounds @jvmancuso?

**Comment by jvmancuso** [comment]
(1) use the user's TF version to selectively import
(2) reproduce the function in TFE to remove the dependency

this function should be pretty easy to reproduce if we'd prefer (2), but this is a general question we should have a default for.

it would also be great to be notified whenever a new release candidate has been cut on TF (ideally in advance, so that we can run tests on it before the release has happened).

**Comment by mortendahl** [comment]
Let's *not* do (1) :)

Re TF RC warning, maybe we simply need to limit the supported version of TF (`tensorflow<=1.13` etc)

**Comment by mortendahl** [comment]
@jvmancuso and @yanndupis could you come up with a longer term solution?

**Comment by jvmancuso** [comment]
Went with (2) above in #545. I suppose limiting <1.14 would work since we plan to move to TF 2.0, but since we don't yet know when those changes will land it's probably best to support the most recent versions if it's low enough effort.
