### ISSUE TITLE
Investigate resource and variant tensors

### ISSUE THREAD

**Issue by mortendahl** [tf-encrypted/tf-encrypted#536]
We need a way to express and operate on memory that's managed outside TensorFlow, for instance to represent ciphertexts from a HE scheme, yet ideally can still be sent across the network using TF mechanisms. This issue investigates to what extent resource and variant tensors could provide this functionality.

**Comment by justin1121** [comment]
I've began my investigation into variant and resource tensors. I've started with variant tensors and here are my findings so far.

**Variant Tensors**

Variant tensors allow any object to be stored inside of a `Tensor` object. From tensorflow documentation it states the object must conform to the following interface:

```
// tensorflow::Variant can store an object of a class that satisfies the
// following constraints:
//
// * The class is CopyConstructible.
// * The class has a default constructor.
// * It's either a protocol buffer, a tensorflow::Tensor, or defines the
// following functions:
//
//   string TypeName() const;
//   void Encode(VariantTensorData* data) const;
//   bool Decode(VariantTensorData data);
```

Where `VariantTensorData` is used for serialization looks like this:

```
//   struct VariantTensorData {
//     string type_name;
//     string metadata;
//     std::vector<Tensor> tensors;
//   };
```

The intention here is that if your object is made up of other tensors than you can easily store them in the tensors vector. Otherwise, your data can be stored inside the metadata field. 

There is also a [VariantOpRegistry](https://github.com/tensorflow/tensorflow/blob/7ed79962bd025062010f82f306719dc17afa3767/tensorflow/core/framework/variant_op_registry.h#L37) which allows the users to register callbacks for decoding variant tensors and sending variant tensors between devices (e.g. cpu to cpu, gpu to gpu) but not between networked devices. From what I can tell is that when networked devices are sent variant tensors using `RecvOp` and `SendOp` they are decoded using the registered decoded function for the type inside the variant. This happens [here](https://github.com/tensorflow/tensorflow/blob/7ed79962bd025062010f82f306719dc17afa3767/tensorflow/core/framework/tensor.cc#L505).

One of the better examples of variants in tensorflow is the `TensorList` object found [here](https://github.com/tensorflow/tensorflow/blob/7ed79962bd025062010f82f306719dc17afa3767/tensorflow/core/kernels/list_kernels.cc#L49). It shows how to implement the interface and also implement the functions need for the variant op registry.

Taking advantage of the decode call back might be an interesting way to manage memory outside of tensorflow. We'll just need a way to make sure the allocated memory gets deallocated at some point.

**Comment by justin1121** [comment]
**Resource Tensor**

A resource tensor does not actually hold on to a resource it just is a handle to a resource. A resource is just any object that subclasses `ResourceBase`. Once added to the `ResourceMgr` the lifetime is either the length of the session or until the resource is removed from the `ResourceMgr`.

From my investigation I could not find anywhere that resources are being sent to other devices other than the ones they are created on. @mortendahl perhaps you've found something around this? Although being able to manage our own resource memory would be beneficial, if resources aren't being sent around automagically than they are of not much use to us.

**Comment by justin1121** [comment]
I think the next steps here are to develop a libgmp POC using variant tensors as a wrapper. libgmp is used in the HE libraries for its bignum operations. This will help give us an idea around how we can make use of the variant tensor.

**Comment by justin1121** [comment]
Opened https://github.com/tf-encrypted/tf-encrypted/issues/536 I think we can close this for now. Let me know if you have any other thoughts @mortendahl .

**Comment by mortendahl** [comment]
Great work @justin1121! Quick question: any idea whether we can use either without re-compiling TensorFlow?

**Comment by justin1121** [comment]
Resources can definitely be used without recompiling tensorflow. I've used them in Tf Trusted (https://github.com/dropoutlabs/tf-trusted/blob/master/tf_trusted_custom_op/model_enclave_op.cc#L44). I don't see any reason why we shouldn't be able to use the variant tensors. We've run into issues registering things in Tensorflow before though right? Maybe something could go wrong there.
