### ISSUE TITLE
tf.split in keras custom layer

### ISSUE THREAD

**Issue by avitalsh** [tf-encrypted/tf-encrypted#561]
Hey @yanndupis 
this is a follow up to the bug I raised in #421. I use tf.split in a keras custom layer - 
```
class customLayer(tf.keras.layers.Layer):
    def __init__(self):
        super(customLayer, self).__init__()

    def build(self, input_shape):
        pass

    def call(self, input, **kwargs):
        return tf.split(input, 3, axis=-1)
```

I use this layer in the following simple model and then I convert it using secure_model
```
input_img = tf.keras.layers.Input(shape=(10,10,3))
x = customLayer()(input_img)
model = tf.keras.Model(inputs=input_img, outputs=x)
model.compile('adam', 'categorical_crossentropy', metrics=['accuracy'])
s_model = secure_model(model)
```

This raises the following error - 

Traceback (most recent call last):
  File "/cs/labs/peleg/avitalsh/CFNAS/CFNAS/test.py", line 33, in <module>
    s_model = secure_model(model)
  File "/cs/labs/peleg/avitalsh/tools/tfe_fork/tf-encrypted/tf_encrypted/private_model.py", line 84, in secure_model
    tfe.convert.registry(), 'input-provider', inputs)
  File "/cs/labs/peleg/avitalsh/tools/tfe_fork/tf-encrypted/tf_encrypted/convert/convert.py", line 104, in convert
    self.outputs[output_name[i]] = out[i]
IndexError: list index out of range

I tried debugging a bit and this is what I found - 
When the converter reach this line - 
https://github.com/tf-encrypted/tf-encrypted/blob/10218935bd7433775f7e0cfc27666881a300f028/tf_encrypted/convert/convert.py#L102

we enter ```find_output_names``` where we list the node names - 
https://github.com/tf-encrypted/tf-encrypted/blob/10218935bd7433775f7e0cfc27666881a300f028/tf_encrypted/convert/convert.py#L327-L328

and this is what I get - 
![image](https://user-images.githubusercontent.com/17612668/59337187-bbb58100-8d08-11e9-9407-b786aea7e202.png)

then when we iterate the list starting from index n_i + 1 which is 3 in this example - but ```node_name_list``` has only 3 items so this for loop is skipped and we end up with an empty list as a return value so ```output_name``` is an empty list
https://github.com/tf-encrypted/tf-encrypted/blob/10218935bd7433775f7e0cfc27666881a300f028/tf_encrypted/convert/convert.py#L102

and then we get the error here, trying to access items in an empty list
https://github.com/tf-encrypted/tf-encrypted/blob/10218935bd7433775f7e0cfc27666881a300f028/tf_encrypted/convert/convert.py#L103-L104

The converter works fine with custom keras layers which use operations that only have one output (such as tf.keras.layers.Relu and tf.keras.layers.Conv2D)

**Comment by yanndupis** [comment]
Hey @avitalsh , thanks for raising this issues. I will fix it on Monday. 

Our test in TF Encrypted pass because in the pb tf.split is not the last node.
https://github.com/tf-encrypted/tf-encrypted/blob/58387f860eb4566277dfc4ad24a83cf2e5296859/tf_encrypted/convert/convert_test.py#L186-L188

When we export the pb file we have this tf.identity op which generates a `Pack` (stack the split output) the node in the pb file. So in this case `find_output_names` return Pack inputs.
https://github.com/tf-encrypted/tf-encrypted/blob/58387f860eb4566277dfc4ad24a83cf2e5296859/tf_encrypted/convert/convert_test.py#L891

But the converter doesn't handle properly the situation where the last node has several outputs. Which is the case with `secure_model` (this Pack node doesn't get generated).

Just curious, did you get an error with split when working with a bigger model where split is not the last operation or just with this toy example?

Thanks

**Comment by avitalsh** [comment]
Hey @yanndupis , thanks!
I tested the following model, where split is not the last node, and did not get any error - 
```
input_img = tf.keras.layers.Input(shape=(10,10,3))
x = customLayer()(input_img)
x = tf.keras.layers.Concatenate(axis=-1)(x)
model = tf.keras.Model(inputs=input_img, outputs=x)
```

I also tested another model that did not get an error, but had wrong output dimensions:
```
input_img = tf.keras.layers.Input(shape=(10,10,3))
x = customLayer()(input_img)
for i in range(3):
    x[i] = tf.keras.layers.ReLU()(x[i])
model = tf.keras.Model(inputs=input_img, outputs=x)
```

**tf.keras output shape: (3, 1, 10, 10, 1)**
**tfe output shape: (1, 10, 10, 1)** - I think it just returns the last relu performed (on x[2]) and not the entire x tensor.
