### ISSUE TITLE
Converting Graphs with multiple Op outputs

### ISSUE THREAD

**Issue by jvmncs** [tf-encrypted/tf-encrypted#585]
Continuation of #572 

See https://github.com/tf-encrypted/tf-encrypted/pull/572#issuecomment-505219938 for details.

**Comment by zjn-code** [comment]
In TFE based on TF2, we convert a model to a onnx model first, then convert this onnx model to TFE model.
Thanks to onnx's model definition, we could easily collect all output tensor as model's output, rather than using an op's output as model's output.
Check code [here](https://github.com/tf-encrypted/tf-encrypted/blob/9f1c0d5ab9a8e485b80cbab39dcd5a41e9d7e28a/tf_encrypted/convert/convert.py#L210) for more info.
