### ISSUE TITLE
Keras API in documentation

### ISSUE THREAD

**Issue by jvmancuso** [tf-encrypted/tf-encrypted#587]
Since Read the Docs/Sphinx doesn't recognize Google style docstrings, our recent work isn't being added to the documentation.  We should fix Sphinx so that it recognizes these docstrings.

**Comment by bendecoste** [comment]
Was the entire project changed to these new style docstrings or just the new keras work?

**Comment by bendecoste** [comment]
I was able to get a doc generated for `keras.layers.Dense` using `autodoc`

```rst
`keras.layers.Dense`
=========

.. autoclass:: tf_encrypted.keras.layers.dense.Dense
  :members:
```

Will generated

![image](https://user-images.githubusercontent.com/1411145/60516103-6b9c5f80-9cb3-11e9-89ab-72626df9dc93.png)


Obviously the spacing here is a little wonky .. we can fix that up with new lines if needed.

Going to look into https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html first, though.

**Comment by bendecoste** [comment]
napoleon worked pretty flawlessly, and even integrates with the older docs that we can eventually roll over

`keras.layers.Dense` renders as

![image](https://user-images.githubusercontent.com/1411145/60516698-a6eb5e00-9cb4-11e9-964e-cfe77af45546.png)

**Comment by bendecoste** [comment]
So we can auto generated the API docs based on all of the files that have docs.  This will render something that looks like

![image](https://user-images.githubusercontent.com/1411145/60517041-59bbbc00-9cb5-11e9-9ea9-136f22e8fc48.png)

I recommend that we do this and remove the extra things in the docs (installing, getting started, etc)., and only have the API docs. We have the website + github for these things, and since we have to rewrite these things for the docs, they go out of date.

**Comment by bendecoste** [comment]
I dug into another possible avenue which I think is interesting.

I was curious about rendering the docs on tf-encrypted.io rather than readthedocs.  I think this is what we would want to do long term and might just be worth setting up right now.  I have hacked together a simple proof of concept that I think shows some promise.  Basically I did the following

- Converted tf-encrypted/website to be a [gatsby](gatsbyjs.org) project rather than next.js.  The reason I did this is for the build/data pipeline.  In nextjs you can't build things from the filesystem and we would need to introduce network calls to build blogs/docs.
  - In gatsby, you can generate pages based on graphql queries, I think this is pretty heavy-handed, as we  can leverage the filesystem pretty easily for now (possible avenue for down the road).  Generating docs will look like this:
- We will have to change the build pipeline of docs very slightly.  It is possible to have the sphinx-build command output json, and with naplean above we introduce one more command (explained above)
- then, we can create a template to render the doc pages

```jsx
render() {
    let content = this.props.pageContext.pageContent
    return (
        <div className='cover'>
            <Header hamburgerClicked={this.showSideMenu.bind(this)}/>
            <div className='content doc' dangerouslySetInnerHTML={{ __html: content.body }} />
        </div>
    )
}
```

This will render a page that looks like this

![image](https://user-images.githubusercontent.com/1411145/60536778-723fcc80-9cdd-11e9-802d-0394a3da4420.png)


The doc output json will basically give you the HTML you want, then we can apply CSS as we see fit

E.g. we can easily make it a bit more on brand:

```scss
// docs.scss
@include font-face(RobotoMono, fonts/RobotoMono-Regular, null, null, ttf)

code {
    color: #06C6A2;
}

h1 {
    font-family: "RobotoMono";
}

h2 {
    font-family: "RobotoMono";
}

.doc {
    padding: 2rem;
    padding-top: 7rem;
}
```

will render 

![image](https://user-images.githubusercontent.com/1411145/60537062-06aa2f00-9cde-11e9-8511-4e5d653fa1ce.png)


Obviously we will need to do a bit more than this.  E.g. making a sidebar, etc

**Comment by bendecoste** [comment]
Another bonus is that this same strategy would work for some other things on the site

e.g. right now the tutorials link back to github, but we could host them on the site, but the content is generated via what is in github source.

Same with a blog, if we decided to start one.

**Comment by ianlivingstone** [comment]
Is there another way to include html content inside react without using this property: dangerouslySetInnerHTML ?

**Comment by bendecoste** [comment]
> Is there another way to include html content inside react without using this property: dangerouslySetInnerHTML ?

No, it is rendered as text otherwise.

**Comment by bendecoste** [comment]
So, have dug around sphinx quite a bit and it kind of seems to me like the best way to do docs is more or less how we are doing them now but with the napolean plugin so we can use google style doc strings.

I spent some time digging in to automatically documenting every file/module, as we have a tendency to forget about the `docs/` dir, but in my opinion this makes the amount of API docs too daunting.  You can set excludes but then you have to remember to do that, so you have the reverse problem of what we have right now.

In summary, we can have either a single `index.rst` directory that just includes

```rst
.. toctree::
  :glob:
  tf_encrypted*
```
and you will generate everything

e.g.

![image](https://user-images.githubusercontent.com/1411145/60620891-c2d52980-9db2-11e9-83cd-df90fe462d4b.png)


Or we can specifically decide what we want to generate

e.g.

```rst
.. toctree::

  keras.layers
  keras.engine
  converter

```
will only make docs for those three modules.

In both cases we can still self host the docs.

cc @mortendahl.  Which would you prefer?

**Comment by mortendahl** [comment]
great investigation @bendecoste! 💪 

> Which would you prefer?

agree that including everything would be too much, so explicitly mentioning modules seems like the best approach. it won't change that much so optimistic that we'll remember to also include new items to the list
