### ISSUE TITLE
Split Pond conv2d into im2col and dot product

### ISSUE THREAD

**Issue by koenvanderveen** [tf-encrypted/tf-encrypted#70]
In the current implementation of conv2d in pond the im2col operation is not a node in our graph. When we split conv2d into two separate nodes, we can re-use the output of im2col in the backward phase, which is computationally  more efficient.

**Comment by zicofish** [comment]
conv2d backwards is now implemented [here](https://github.com/tf-encrypted/tf-encrypted/blob/ed3e3ffc2c0e903feb1dd7faaadce32aeedd7fa9/tf_encrypted/keras/layers/convolutional.py#L189)
im2col inside does not seem to be re-usable because it is called with different inputs.

Closing this now. We can continue the discussion in a new issue if needed.
