### ISSUE TITLE
Some comments on the Pond implementation

### ISSUE THREAD

**Issue by Arash-Afshar** [tf-encrypted/tf-encrypted#749]
While reading pond.py, noticed the following. Let me know if I should create multiple issues for them. Also, I can submit a PR with the fixes if you agree with the problems.

1. Confusing input arguments `crypto_producer` and `triple_source`

- passing both crypto_producer and triple_source      -> ignores crypto_prodcuer
- passing crypto_producer and not triple_source         -> creates triple_source from crypto_producer
- passing neither crypto_producer nor triple_source -> will look for "server2" or "crypto-producer" in the config. If none of them is found, no error is returned
- crypto_producer is not an instance variable, yet it is accessed on 

https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/pond.py#L3836

and

https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/pond.py#L4273

2. In `define_private_placeholder`, the expectation is that only one party can access the placeholder. I expected the graph to be created on one of the devices but it is created on both devices.

3. In the `share_output` of `define_local_computation`, the share and wrap can be moved to the `if not masked` branch to save unnecessary computation.

https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/pond.py#L576-L580

4. A general question which came to my mind when reading the comment in `result_wrapper`

https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/pond.py#L683-L687

Do you have tests that can track data leakage? For example, if one were to return `op` without wrapping it in a `tf.group` would anything catch the error?

**Comment by mortendahl** [comment]
> Confusing input arguments `crypto_producer` and `triple_source`.

I agree. Much of this was planned to be part of a larger refactoring, leaving only the triple source (and with better documentation of how Pond should be used). The use of `crypto_producer` later is definitely a bug though, feel free to open issue/PR to fix that! 💪 

> In `define_private_placeholder`, the expectation is that only one party can access the placeholder. I expected the graph to be created on one of the devices but it is created on both devices.

It is creating a placeholder for each share, hence one of each server. See e.g. the `PondPrivatePlaceholder` class which abstracts this.

> In the `share_output` of `define_local_computation`, the share and wrap can be moved to the if not masked branch to save unnecessary computation.

`x` is also used by the else-branch: https://github.com/tf-encrypted/tf-encrypted/blob/2edd1b7b217001ad24acb9bb637e90e6cee4ee70/tf_encrypted/protocol/pond/pond.py#L585. Note that even if it hasn't, since we are constructing a static graph, pruning would make sure that no unneeded operations were executed.

> Do you have tests that can track data leakage? For example, if one were to return op without wrapping it in a `tf.group` would anything catch the error?

Great suggestion! We don't at this point, again mostly due to postponed refactoring, but should definitely have tests for this. There is on-going work to build a hardened version of the TF runtime, which will also touch on this. Orthogonal to this we've also been working on a way to catch leakage in the user's code (as opposed to in the compiler).

**Comment by Arash-Afshar** [comment]
Thanks for the review @mortendahl. I created an issue and submitted the fix for item 1. Feel free to close this issue. Not sure if we need an issue to tackle item 4 or if you already have issues for it.

**Comment by mortendahl** [comment]
Good idea! I've created https://github.com/tf-encrypted/tf-encrypted/issues/760 to follow up on this.
